### PR TITLE
Change isWeekend() check to isWorkingDay() and fallback to Saturday/Sunday as weekend

### LINKED ISSUE #4260: [Visual glitch] Weekend days highlight in `Weekly hours` view are wrong if first day of week is Sunday
### Describe the issue

I think the title says it all. This is a pretty simple visual glitch.

When the user preference uses `Sunday` as first day of week, the `Weekly Hours` view highlight the last two columns, which are `Fri` and `Sat`.

### I already tried

- [X] I've read and searched [the documentation](https://www.kimai.org/documentation/).
- [X] I've searched for similar issues in this repository.
- [X] I've searched for similar issues in [the discussions](https://github.com/kimai/kimai/discussions).

### Kimai version

2.0.26

### How do you run Kimai?

Docker

### Which PHP version are you using?

8.1

### Screenshots

image

### PR DESCRIPTION
**Pull request by sharky98**
## Description
`format('w')` always returns `0` for Sunday and `6` for Saturday. The user configuration will not affect the result.

NOTE: I did not check the side-effects where "isWeekend()" is used elsewhere.

fixes #4260

## Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [ ] I verified that my code applies to the guidelines (`composer code-check`)
    - I edited the code removal from Github editor. I have no PHP dev environment.
- [X] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [X] I agree that this code is used in Kimai (see [license](https://github.com/kimai/kimai/blob/main/LICENSE))

### CODE REVIEW

**Comment by kevinpapst** [comment]
Can you elaborate, maybe it is too late and I don't get it...

I am not living in a place where Sunday is the first day of the week, so I might be mistaken.
But I thought that if Sunday is FDOW than your weekend is friday (5) and saturday (6).
While if Monday is FDOW your weekend is saturday (6) and sunday (0).

Hence the check for different numbers if a user has FDOW = sunday.

**Comment by sharky98** [comment]
I am in Canada, where we use Sunday as the first day of the week. However, this has nothing to do with the weekend days, they are still Saturday and Sunday. This only affects how the calendar is shown.

https://www.timeanddate.com/calendar/days/first-day-of-the-week.html

https://www.wheniscalendars.com/wp-content/uploads/2022/10/august-2023-calendar-printable-by-month-wk-a4-ls-color-wheniscalendars-com_Page_08-1024x724.png

https://calendarkart.com/wp-content/uploads/2023/02/August-2023-Monday-Start-Calendar-1536x1086.jpg

**Comment by kevinpapst** [comment]
Quote from the article:

> For this reason, many Muslim countries had their weekend on Thursday and Friday and would start the week on Saturday.

Which would be okay as third option, but then:

> This changed in 2000 when Jordan shifted to the Friday-Saturday weekend. Since then, most countries in the Middle East and other Muslim-majority countries have switched to the Friday-Saturday weekend. They start their work week on Sunday.

Argh, which is like it is currently handled. Considering that most paying customers do not come from middle east countries I don't mind switching to your proposal. But why can't it be easy for once ???

**Comment by sharky98** [comment]
Yeah, I understand. In a future feature, maybe having a configurable off day? Knowing that more and more people are working 4 days a week and such. It should cover all cases where weekends are not Saturday and Sunday.

**Comment by kevinpapst** [comment]
That is actually a brilliant idea 👍  

Instead of concentrating on the classical approach of a 5-day week we should check whether someone has a working-hour configuration (the `Employment contract`) for the given day: 
Bildschirmfoto 2023-08-31 um 10 19 54

Which should be fairly easy, but we need to reintroduce the `Security` which you just removed, because we need to access the current user.

File: src/Twig/LocaleFormatExtensions.php [hunk 1]
```diff
@@ -115,30 +117,28 @@ public function getLocale(): string
 
         return $this->locale;
     }
-
+
```
Comment (kevinpapst) [inline src/Twig/LocaleFormatExtensions.php]:
```suggestion

```

**Review by kevinpapst — APPROVED** [review]
Thanks for the idea and input @sharky98 👍
