### PR TITLE
fix: billable not respected in api post request

### LINKED ISSUE #3254: API Timesheet/Post -> billable=false not processed
When using the API for timesheet post, the billable=false is not applied (version 1.19.2, it is working on 1.16.10).

**To Reproduce**

Request header:

activity: "23"
begin: "2022-04-07 12:45"
**billable: false**
description: ""
end: "2022-04-07 17:00"
project: "20"

Response:

activity: 23
begin: "2022-04-07T12:45:00+0200"
**billable: true**
description: null
duration: 15300
end: "2022-04-07T17:00:00+0200"
exported: false
fixedRate: null
hourlyRate: 0
id: 314
internalRate: 0
metaFields: []
project: 20
rate: 0
tags: []
user: 14

**Additional context**
 - Kimai version: 1.19.2 
 - PHP version: 7.4.25

### PR DESCRIPTION
**Pull request by j0hannesr0th**
## Description
A clear and concise description of what this pull request adds or changes.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist
- [x] I verified that my code applies to the guidelines (`composer code-check`)
- [ ] I updated the documentation (see [here](https://github.com/kimai/www.kimai.org/tree/master/_documentation))
- [x] I agree that this code is used in Kimai and will be published under the [MIT license](https://github.com/kevinpapst/kimai2/blob/master/LICENSE)

fixed #3254

### CODE REVIEW

File: src/Form/API/TimesheetApiEditForm.php [hunk 1]
```diff
@@ -24,6 +28,22 @@ protected function addBillable(FormBuilderInterface $builder, array $options)
         }
 
         $builder->add('billable', BillableType::class, []);
+
+        $builder->addEventListener(
+            FormEvents::PRE_SUBMIT,
+            function (FormEvent $event) {
+                $data = $event->getData();
+                if (array_key_exists('billable', $data)) {
```
Comment (kevinpapst) [inline src/Form/API/TimesheetApiEditForm.php]:
```suggestion
                if (\array_key_exists('billable', $data)) {
```

**Review by kevinpapst — APPROVED** [review]
Tricky fix 👍 LGTM

**Comment by kevinpapst** [comment]
Thanks @j0hannesr0th 😄
